### ISSUE TITLE
Gesture Method Not Working

### ISSUE THREAD

**Issue by searchy2** [Ivaskuu/tinder_cards#2]
When switching to the gesture detection with the app bar switch, swiping does not work. 
What could be the issue?

**Comment by searchy2** [comment]
Hmm, it seems that the code for gesture detection is not included. That's a bit disappointing :(

**Comment by Ivaskuu** [comment]
Hi! Which one are you talking about? All the app source code was uploaded here.

Are you maybe talking about this?

```
new GestureDetector (
// While dragging the first card
onPanUpdate: (DragUpdateDetails details) {
// Add what the user swiped in the last frame to the alignment of the card
setState(() {
// 20 is the "speed" at which moves the card
frontCardAlign = new Alignment(
frontCardAlign.x + 20 * details.delta.dx / MediaQuery.of(context).size.width,
frontCardAlign.y + 40 * details.delta.dy / MediaQuery.of(context).size.height);
frontCardRot = frontCardAlign.x; // * rotation speed;
});
},

// When releasing the first card
onPanEnd: (_) {
// If the front card was swiped far enough to count as swiped
if(frontCardAlign.x > 3.0 || frontCardAlign.x < -3.0) {
animateCards();
}
else {
// Return to the initial rotation and alignment
setState(() {
frontCardAlign = defaultFrontCardAlign;
frontCardRot = 0.0;
});
}}),
```

**Comment by searchy2** [comment]
Wow, this how Github is supposed to work. Thanks @edgartrem for finding the bug and @Ivaskuu for leaving this issue open even though you didn't think the issue was really there. Fantastic!

**Comment by JillevdW** [comment]
Good to see this issue was fixes for you, but since the code in the repository isn't fixed yet I don't feel like we should close this issue yet. I've made a small pull request to fix the issue with the solution provided by @edgartrem :) #7
